In [320]:
!pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [321]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore") 
import yfinance as yf
yf.pdr_override()

In [322]:
symbol = 'AMD'
start = '2021-08-20'
end = '2022-08-20'
dataset = yf.download(symbol,start,end)
dataset.tail()

[*********************100%***********************]  1 of 1 completed


Open        High        Low       Close   Adj Close  \
Date                                                                    
2022-08-15  100.510002  101.849998  99.800003  101.010002  101.010002   
2022-08-16  100.839996  101.449997  98.320000  100.199997  100.199997   
2022-08-17   99.260002   99.639999  96.730003   98.269997   98.269997   
2022-08-18   97.739998  101.070000  96.730003  100.440002  100.440002   
2022-08-19   98.669998   99.250000  94.589996   95.949997   95.949997   

              Volume  
Date                  
2022-08-15  61327100  
2022-08-16  60220700  
2022-08-17  63735600  
2022-08-18  76059500  
2022-08-19  67167500

In [323]:
dataset['Returns'] = dataset['Adj Close'].pct_change() 
dataset['Returns'] = dataset['Adj Close'].dropna()

In [324]:
Returns = np.array(dataset['Returns'])
Open = np.array(dataset['Open'])
Close = np.array(dataset['Adj Close'])
High = np.array(dataset['High'])
Low = np.array(dataset['Low'])

In [325]:
Close = np.round(Close, 2)
Close

array([104.65, 108.77, 107.65, 108.3 , 107.27, 111.4 , 111.32, 110.72,
       109.99, 109.2 , 109.92, 109.15, 106.17, 106.15, 105.2 , 104.8 ,
       105.73, 105.6 , 106.22, 103.88, 101.55, 102.82, 104.38, 106.15,
       105.8 , 108.16, 101.52, 100.35, 102.9 , 102.45, 100.34, 101.81,
       103.64, 106.45, 105.06, 104.68, 105.04, 109.16, 111.99, 112.12,
       116.43, 116.33, 116.39, 119.33, 119.82, 122.36, 122.93, 122.28,
       121.16, 120.23, 125.23, 127.63, 130.53, 137.5 , 136.34, 150.16,
       148.92, 139.87, 146.01, 147.89, 146.49, 152.45, 151.34, 155.02,
       155.41, 152.52, 149.92, 157.8 , 154.81, 161.91, 158.37, 149.11,
       150.68, 144.01, 139.06, 144.85, 145.24, 138.1 , 138.55, 133.8 ,
       135.6 , 146.5 , 138.64, 137.75, 135.8 , 144.25, 143.88, 146.14,
       154.36, 153.15, 148.26, 145.15, 143.9 , 150.24, 144.42, 136.15,
       136.23, 132.  , 132.  , 137.31, 137.47, 132.74, 136.88, 131.93,
       128.27, 121.89, 118.81, 116.53, 111.13, 110.71, 102.6 , 105.24,
      

In [326]:
import collections
print([item for item, count in collections.Counter(Close).items() if count > 1])

[106.15, 132.0, 113.83, 86.99]


**Vectors (Rank 1 Tensors) in NumPy**

In [327]:
x = [item for item, count in collections.Counter(Close).items() if count > 1]
x

[106.15, 132.0, 113.83, 86.99]

In [328]:
x = np.array(x)
x

array([106.15, 132.  , 113.83,  86.99])

In [329]:
 len(x)

4

In [330]:
x.shape

(4,)

In [331]:
type(x)

numpy.ndarray

In [332]:
x[0]

106.15

In [333]:
type(x[0])

numpy.float64

**Vector Transposition**

In [334]:
x_t = x.T
x_t

array([106.15, 132.  , 113.83,  86.99])

In [335]:
x_t.shape

(4,)

In [336]:
Open = np.round(Open, 2)
Open

array([104.32, 105.3 , 109.45, 108.13, 108.57, 108.01, 112.61, 111.26,
       111.3 , 110.32, 108.85, 109.96, 108.88, 106.56, 106.99, 105.26,
       105.52, 106.  , 104.92, 105.56, 101.58, 102.15, 102.82, 104.89,
       105.19, 105.07, 106.84, 102.3 , 102.08, 102.6 , 101.74, 100.92,
       100.45, 104.6 , 106.55, 104.62, 105.17, 106.28, 110.5 , 112.51,
       111.9 , 116.16, 116.29, 116.5 , 120.83, 120.52, 122.99, 121.63,
       122.86, 120.95, 119.45, 124.98, 127.75, 132.01, 139.19, 137.7 ,
       154.01, 143.93, 142.96, 146.03, 148.  , 145.93, 151.98, 157.07,
       155.76, 157.14, 150.41, 149.46, 155.8 , 157.5 , 163.28, 160.37,
       147.68, 151.65, 141.14, 143.9 , 144.96, 145.16, 141.29, 138.25,
       131.67, 135.11, 147.  , 136.3 , 135.97, 138.19, 142.65, 143.89,
       147.51, 155.88, 152.82, 147.44, 146.16, 145.14, 151.01, 142.82,
       136.19, 136.28, 129.08, 133.45, 138.59, 139.44, 131.68, 134.5 ,
       133.55, 126.04, 120.14, 115.4 , 114.1 , 114.55, 111.96, 101.55,
      

In [337]:
y = [item for item, count in collections.Counter(Open).items() if count > 1]
y

[108.13]

In [338]:
y = np.array([y])

In [339]:
y.shape

(1, 1)

In [340]:
y_t = y.T
y_t

array([[108.13]])

In [341]:
y_t.shape 

(1, 1)

In [342]:
y_t.T 

array([[108.13]])

In [343]:
y_t.T.shape

(1, 1)

**Torch and Tensorflow**

In [344]:
import torch
import tensorflow as tf

In [345]:
x_pt = torch.tensor(x)
x_pt

tensor([106.1500, 132.0000, 113.8300,  86.9900], dtype=torch.float64)

In [346]:
x_tf = tf.Variable(x)
x_tf

<tf.Variable 'Variable:0' shape=(4,) dtype=float64, numpy=array([106.15, 132.  , 113.83,  86.99])>

**L Square Norm**

In [347]:
x

array([106.15, 132.  , 113.83,  86.99])

In [348]:
np.linalg.norm(x)

221.84758619376504

In [349]:
np.dot(x,x)

49216.351500000004

**Max Norm**

In [350]:
np.max([np.abs(x)])

132.0

**Orthogonal Vectors**

In [351]:
i = np.array([x])
i = i.T
i.shape

(4, 1)

In [352]:
j = np.array(y)
j.shape

(1, 1)

In [353]:
np.dot(i, j)

array([[11477.9995],
       [14273.16  ],
       [12308.4379],
       [ 9406.2287]])

**Convert Array to 2-D Matrix**

In [354]:
x

array([106.15, 132.  , 113.83,  86.99])

In [355]:
x.shape

(4,)

In [356]:
arr_2d = np.reshape(x, (-1, 1))

In [357]:
print('1D Numpy array:')
print(x)
print("\n")
print('2D Numpy array:')
print(arr_2d)

1D Numpy array:
[106.15 132.   113.83  86.99]


2D Numpy array:
[[106.15]
 [132.  ]
 [113.83]
 [ 86.99]]


In [358]:
arr_2d.shape

(4, 1)

In [359]:
arr_2d.size

4

In [360]:
arr_2d[:,0]

array([106.15, 132.  , 113.83,  86.99])

In [361]:
arr_2d[1,:]

array([132.])

In [362]:
arr_2d[0:2, 0:2]

array([[106.15],
       [132.  ]])

**Matrices in PyTorch**

In [363]:
X_pt = torch.tensor(arr_2d)
X_pt

tensor([[106.1500],
        [132.0000],
        [113.8300],
        [ 86.9900]], dtype=torch.float64)

In [364]:
X_pt.shape

torch.Size([4, 1])

In [365]:
X_pt[1,:]

tensor([132.], dtype=torch.float64)

**Matrices in TensorFlow**

In [366]:
X_tf = tf.Variable(arr_2d)
X_tf

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float64, numpy=
array([[106.15],
       [132.  ],
       [113.83],
       [ 86.99]])>

In [367]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [368]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 1], dtype=int32)>

In [369]:
X_tf[1,:]

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([132.])>

**Matrix Transposition**

In [370]:
X = arr_2d
X

array([[106.15],
       [132.  ],
       [113.83],
       [ 86.99]])

In [371]:
X.T

array([[106.15, 132.  , 113.83,  86.99]])

In [372]:
X_pt.T

tensor([[106.1500, 132.0000, 113.8300,  86.9900]], dtype=torch.float64)

**Matrix Multiplication**

In [373]:
X*3

array([[318.45],
       [396.  ],
       [341.49],
       [260.97]])

In [374]:
X*3+3

array([[321.45],
       [399.  ],
       [344.49],
       [263.97]])

In [375]:
X_pt*3+3

tensor([[321.4500],
        [399.0000],
        [344.4900],
        [263.9700]], dtype=torch.float64)

**Hadamard product** 

In [376]:
A = np.reshape(y, (-1, 1))
A 

array([[108.13]])

In [377]:
X

array([[106.15],
       [132.  ],
       [113.83],
       [ 86.99]])

In [378]:
X * A

array([[11477.9995],
       [14273.16  ],
       [12308.4379],
       [ 9406.2287]])

In [379]:
A_p = torch.tensor(A)
A_p

tensor([[108.1300]], dtype=torch.float64)

In [380]:
X_pt * A_p

tensor([[11477.9995],
        [14273.1600],
        [12308.4379],
        [ 9406.2287]], dtype=torch.float64)

In [381]:
X = X.T
np.dot(A, X)

array([[11477.9995, 14273.16  , 12308.4379,  9406.2287]])

In [382]:
b_p = torch.tensor(X)
b_p

tensor([[106.1500, 132.0000, 113.8300,  86.9900]], dtype=torch.float64)

In [383]:
torch.matmul(A_p, b_p)

tensor([[11477.9995, 14273.1600, 12308.4379,  9406.2287]], dtype=torch.float64)

**Matrix Inversion**

In [384]:
arr_2d 

array([[106.15],
       [132.  ],
       [113.83],
       [ 86.99]])

In [385]:
X = np.array([[2, 8], [-5, -6]])
X

array([[ 2,  8],
       [-5, -6]])

In [386]:
Xinv = np.linalg.inv(X)
Xinv

array([[-0.21428571, -0.28571429],
       [ 0.17857143,  0.07142857]])

In [387]:
y = np.array([3, -5])
y

array([ 3, -5])

In [388]:
w = np.dot(Xinv, y)
w

array([0.78571429, 0.17857143])

In [389]:
np.dot(X, w)

array([ 3., -5.])

In [390]:
X_p = torch.tensor([[5, 10], [-6, -8.]]) 
X_p

tensor([[ 5., 10.],
        [-6., -8.]])

In [391]:
Xinv_p = torch.inverse(X_p)
Xinv_p

tensor([[-0.4000, -0.5000],
        [ 0.3000,  0.2500]])

In [392]:
y_p = torch.tensor([4, -7.])
y_p

tensor([ 4., -7.])

In [393]:
w_p = torch.matmul(Xinv_p, y_p)
w_p

tensor([ 1.9000, -0.5500])

In [394]:
torch.matmul(X_p, w_p)

tensor([ 4.0000, -7.0000])